"""add lgd_code, subdistrict, and village

Revision ID: 49ee9f0b3eb8
Revises: c2643efbc202
Create Date: 2026-09-28 22:08:23.279902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ee9f0b3eb8'
down_revision: Union[str, None] = 'c2643efbc202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdistricts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'code', name='uix_district_subdistrict_code')
    )
    op.create_index(op.f('ix_subdistricts_id'), 'subdistricts', ['id'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdistrict_id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['subdistricts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_code'), 'villages', ['code'], unique=True)
    op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
    op.create_index(op.f('ix_villages_name'), 'villages', ['name'], unique=False)
    op.create_index(op.f('ix_villages_subdistrict_id'), 'villages', ['subdistrict_id'], unique=False)
    op.add_column('districts', sa.Column('lgd_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_districts_lgd_code'), 'districts', ['lgd_code'], unique=False)
    op.add_column('states', sa.Column('lgd_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_states_lgd_code'), 'states', ['lgd_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_lgd_code'), table_name='states')
    op.drop_column('states', 'lgd_code')
    op.drop_index(op.f('ix_districts_lgd_code'), table_name='districts')
    op.drop_column('districts', 'lgd_code')
    op.drop_index(op.f('ix_villages_subdistrict_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_code'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_subdistricts_id'), table_name='subdistricts')
    op.drop_table('subdistricts')
    # ### end Alembic commands ###
