"""initial

Revision ID: c2643efbc202
Revises: 
Create Date: 2026-09-27 23:27:40.889193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2643efbc202'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('crop_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('optimal_temp_min_c', sa.Float(), nullable=True),
    sa.Column('optimal_temp_max_c', sa.Float(), nullable=True),
    sa.Column('water_requirement_mm', sa.Float(), nullable=True),
    sa.Column('critical_stages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_profiles_id'), 'crop_profiles', ['id'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_id'), 'ingestion_logs', ['id'], unique=False)
    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('mae_temp_c', sa.Float(), nullable=True),
    sa.Column('rmse_temp_c', sa.Float(), nullable=True),
    sa.Column('r2_temp', sa.Float(), nullable=True),
    sa.Column('rain_precision', sa.Float(), nullable=True),
    sa.Column('rain_recall', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_versions_id'), 'ml_model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_model_versions_version_name'), 'ml_model_versions', ['version_name'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_code'), 'states', ['code'], unique=True)
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=False)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_code'), 'blocks', ['code'], unique=False)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_table('block_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('lead_time_hours', sa.Integer(), nullable=True),
    sa.Column('temp_min_c', sa.Float(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('precipitation_prob_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_forecasts_forecast_date'), 'block_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_block_forecasts_id'), 'block_forecasts', ['id'], unique=False)
    op.create_table('panchayats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('aspect', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panchayats_code'), 'panchayats', ['code'], unique=False)
    op.create_index(op.f('ix_panchayats_id'), 'panchayats', ['id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('temp_min_c', sa.Float(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('source_provider', sa.String(), nullable=True),
    sa.Column('is_live', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_timestamp'), 'weather_observations', ['timestamp'], unique=False)
    op.create_table('agricultural_advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('growth_stage', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_hi', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('recommended_action_hi', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('weather_trigger', sa.String(length=200), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agricultural_advisories_id'), 'agricultural_advisories', ['id'], unique=False)
    op.create_table('downscaled_panchayat_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=False),
    sa.Column('block_forecast_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('temp_min_c', sa.Float(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('temp_avg_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('precipitation_prob_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('uncertainty_margin_c', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('provider_source', sa.String(), nullable=True),
    sa.Column('is_simulated', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_forecast_id'], ['block_forecasts.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downscaled_panchayat_forecasts_forecast_date'), 'downscaled_panchayat_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_downscaled_panchayat_forecasts_id'), 'downscaled_panchayat_forecasts', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('primary_crop', sa.String(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('irrigation_type', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_downscaled_panchayat_forecasts_id'), table_name='downscaled_panchayat_forecasts')
    op.drop_index(op.f('ix_downscaled_panchayat_forecasts_forecast_date'), table_name='downscaled_panchayat_forecasts')
    op.drop_table('downscaled_panchayat_forecasts')
    op.drop_index(op.f('ix_agricultural_advisories_id'), table_name='agricultural_advisories')
    op.drop_table('agricultural_advisories')
    op.drop_index(op.f('ix_weather_observations_timestamp'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_panchayats_id'), table_name='panchayats')
    op.drop_index(op.f('ix_panchayats_code'), table_name='panchayats')
    op.drop_table('panchayats')
    op.drop_index(op.f('ix_block_forecasts_id'), table_name='block_forecasts')
    op.drop_index(op.f('ix_block_forecasts_forecast_date'), table_name='block_forecasts')
    op.drop_table('block_forecasts')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_code'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_index(op.f('ix_states_code'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_ml_model_versions_version_name'), table_name='ml_model_versions')
    op.drop_index(op.f('ix_ml_model_versions_id'), table_name='ml_model_versions')
    op.drop_table('ml_model_versions')
    op.drop_index(op.f('ix_ingestion_logs_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_crop_profiles_id'), table_name='crop_profiles')
    op.drop_table('crop_profiles')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
